### ISSUE TITLE
the ingestor crashes after about 6 hours

### ISSUE THREAD

**Issue by derekhillhp** [adaptivethreat/BloodHound#34] opened 2016-08-16 15:43 UTC
I am trying to run the PS ingestor on a large domain (~50,000 users), and the PS ingestor crashes with out of memory errors. This is a machine with 32GB of ram.

The command used was: 

Get-BloodHoundData | Export-BloodHoundCSV -CSVFolder c:\bloodhound\my-csv

The only file generated was:

group_memberships.csv with a file size of 1600kb and it contains 19433 rows of data.

Here are the errors (some of them, they were repeated)

Add-Member : Cannot validate argument on parameter 'NotePropertyName'. Exception of type 'System.OutOfMemoryException'
was thrown.
At C:\BloodHound\PowerShell\BloodHound.ps1:5571 char:47
+                     $GroupMember | Add-Member Noteproperty 'DNSHostNa ...
+                                               ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.AddMemberCommand

Exception of type 'System.OutOfMemoryException' was thrown.
At C:\BloodHound\PowerShell\BloodHound.ps1:795 char:5
+     $ObjectCSV = $InputObject | ConvertTo-Csv -NoTypeInformation
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], OutOfMemoryException
    + FullyQualifiedErrorId : System.OutOfMemoryException

Exception of type 'System.OutOfMemoryException' was thrown.
At C:\BloodHound\PowerShell\BloodHound.ps1:803 char:9
+         $ObjectCSV | ForEach-Object { $Start=$True }{ if ($Start) {$S ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], OutOfMemoryException
    + FullyQualifiedErrorId : System.OutOfMemoryException

Exception of type 'System.OutOfMemoryException' was thrown.
At C:\BloodHound\PowerShell\BloodHound.ps1:5505 char:25
+                         $GroupMember = New-Object PSObject
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], OutOfMemoryException
    + FullyQualifiedErrorId : System.OutOfMemoryException

**Comment by rvazarkar** [comment] 2016-08-16 17:55
Duplicate of #7

**Closed by rvazarkar** 2016-08-16 17:55 UTC
