### ISSUE TITLE
WARNING: Error converting - null value expression

### ISSUE THREAD

**Issue by ActualReverend** [adaptivethreat/BloodHound#19] opened 2016-08-09 20:34 UTC
PS N:\BloodHoundCSVs> Get-BloodhoundData | Export-BloodHoundCSV
WARNING: Error converting
CN=S-1-5-21-somenumbershereremoved-somenumbershereremoved-somenumbershereremoved-somenumbershereremove,CN=ForeignSecurityPrincipals,DC=domainname,DC=upperforestname,DC=domainnamehere,DC=dnssuffixhere
You cannot call a method on a null-valued expression.
At N:\Bloodhound\PowerShell\BloodHound.ps1:5433 char:21
+                     $Members = $Result.properties.item("member")
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by Beercow** [comment] 2016-08-10 16:06
The WARNING: Error converting message appears to be caused by the SID not having a readable name. Hope this solves part of your problem.

**Comment by ActualReverend** [comment] 2016-08-10 19:12
I was doing a bit of research on "ForeignSecurityPrincipals", and one of my domain had lots of them... but only one errors, and most don't have a readable name.  I was thinking maybe there was a limitation in the string size or something of that variable, but I dunno.

**Comment by HarmJ0y** [comment] 2016-08-10 21:14
Try repulling from master and retrying, we just pushed some updates to the ingestor logic.

**Comment by HarmJ0y** [comment] 2016-08-10 21:15
Also, is this a duplicate of https://github.com/adaptivethreat/BloodHound/issues/20 ?

**Comment by ActualReverend** [comment] 2016-08-10 21:34
No, Sir, I have an "error" and a "warning," two different things.   (Thank you for this tool btw, we are all very excited to use it, so DC25 I owe you a drink!)

**Comment by HarmJ0y** [comment] 2016-08-25 20:18
We just landed https://github.com/adaptivethreat/BloodHound/pull/38 , is this applicable?

**Comment by rvazarkar** [comment] 2016-10-10 04:35
Closing this due to lack of activity

**Closed by rvazarkar** 2016-10-10 04:35 UTC
