### ISSUE TITLE
Find Shortest Path to Domain Admins does not load

### ISSUE THREAD

**Issue by adamwestland** [adaptivethreat/BloodHound#45] opened 2016-09-08 17:18 UTC
I have a large db with many objects and most of the queries load in a few seconds, however "Find Shortest Path to Domain Admins" doesn't load. The **Querying Database** animation loops in the bottom left corner but nothing appears to be happening. This persists across reboots. Server is 2012 R2, 128 GB RAM and 8 CPU.

Any ideas?

**Comment by HarmJ0y** [comment] 2016-09-08 19:31
Can you give us an idea on the number of computers/users/relationships in your database?

**Comment by adamwestland** [comment] 2016-09-09 18:10
about 70K users, 20K computers, with 485K relationships

**Comment by rvazarkar** [comment] 2016-09-11 15:33
So I've been unable to track down what exactly causes it, but for extremely large queries, it looks like neo4j can sometimes just fail to send all the data. Usually the error we get on our end is Unexpected End of JSON. I'm going to take a look and see if I can come up with a workaround or a fix for this.

**Comment by rvazarkar** [comment] 2016-09-15 20:30
After further investigation, it looks like either neo4j or the javascript engine is running out of memory. Fun times. I'm working on a potential fix to this, but its not an easy or quick fix unfortunately

**Comment by rvazarkar** [comment] 2016-09-23 16:08
I just pushed a beta for the 1.1 release. In my testing, this should actually fix this issue for horrifically large databases. Not quite ready to finalize the release, but feel free to test on the beta

https://github.com/adaptivethreat/BloodHound/releases/tag/v1.1

**Comment by rvazarkar** [comment] 2016-10-10 04:36
Hopefully should be fixed in 1.1, closing this due to lack of response

**Closed by rvazarkar** 2016-10-10 04:36 UTC

**Comment by phocean** [comment] 2017-12-06 16:00
I think I am having the same issue with release 1.4.
It was tested by me and other people against various environments, including a tiny test domain.
The request seems to never load, there is a central waiting animation which never ends and nothing happens.

**Comment by meldridge** [comment] 2018-03-06 07:36
I'm having this issue on 1.4 as well. I've tried it on two domains (one is only a couple of dozen endpoints), and I just get the "Querying Database" which never completes.

**Comment by meldridge** [comment] 2018-03-06 08:48
I've tried running the query locally on neo4j, and it gives me this error: 

![capture](https://user-images.githubusercontent.com/8285554/37022533-8b14fb4a-2123-11e8-8302-3f5517773cee.PNG)

With a different domain, exactly the same error:

![capture2](https://user-images.githubusercontent.com/8285554/37022517-81e831fe-2123-11e8-8e87-7273ab118512.PNG)

**Comment by meldridge** [comment] 2018-03-06 16:18
Should clarify: this is the latest Community version of neo4j (3.3.3), and when I say "different domain", I mean I did a "Clear Database" from within BloodHound itself, and then imported the CSVs for the second domain.

**Comment by meldridge** [comment] 2018-03-06 16:34
Solved with the help of @rvazarkar: it looks like this was caused by a corrupted DB. Completely nuking the graphs.db folder and letting node4j create a new one solved the problem. (Thanks Rohan).

For anyone else with this issue: the neo4j database sits in data/databases/graph.db. If you rename that folder and create an empty one called "graph.db", then restart neo4j, it should fix the problem.
