### ISSUE TITLE
Export-BloodHoundData : Cannot validate argument on parameter 'SID'

### ISSUE THREAD

**Issue by adamwestland** [adaptivethreat/BloodHound#37] opened 2016-08-18 17:00 UTC
Running the following command: `Get-BloodHoundData -Verbose -CollectionMethod 'Stealth' | foreach-object { write-verbose "Obj: $($_.cn)"; $_ } | Export-BloodHoundData -URI http://localhost:7474 -UserPass "neo4j:BloodHound" -Verbose`

It runs for many hours and I see data until eventually it halts with the following error:

Export-BloodHoundData : Cannot validate argument on parameter 'SID'. The argument "" does not match the "^S-1-.*"
pattern. Supply an argument that matches "^S-1-.*" and try the command again.
At line:1 char:114
+ Get-BloodHoundData -Verbose -CollectionMethod 'Stealth' | foreach-object { write ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-BloodHoundData], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Export-BloodHoundData

**Comment by adamwestland** [comment] 2016-08-19 15:40
I suspect this is just a bad object in the domain I'm scanning, but it doesn't show me which object it is. Any ideas on how I can track it down or get it displayed to the screen?

**Comment by egru** [comment] 2016-08-19 19:07
This was happening to me too. It was caused by grabbing the groups.xml from sysvol, at least for me. I fixed it by adding in a check for null/empty SIDs in the Export-BloodHoundData function:

elseif($Object.PSObject.TypeNames -contains 'PowerView.GPOLocalGroup') {
               
                 if(![string]::IsNullOrEmpty($Object.SID)){
                    $MemberSimpleName = Convert-SidToName -SID $Object.SID | Convert-ADName -InputType 'NT4' -OutputType 'Canonical'

**Comment by adamwestland** [comment] 2016-08-20 13:54
That worked perfectly! Thank you so much

**Comment by HarmJ0y** [comment] 2016-08-25 20:01
Should hopefully be fixed with https://github.com/adaptivethreat/BloodHound/pull/38, feel free to reopen if there's still an issue.

**Closed by HarmJ0y** 2016-08-25 20:01 UTC
