### ISSUE TITLE
Export-BloodHoundData - UploadString error locally

### ISSUE THREAD

**Issue by Beercow** [adaptivethreat/BloodHound#21] opened 2016-08-10 15:37 UTC
Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474/ -UserPass "neo4j:BloodHound"

Produces the following error:
Exception calling "UploadString" with "2" argument(s): "The remote server returned an error: (500) Internal Server Error."
At C:\Users\user\Downloads\BloodHound-master\BloodHound-master\PowerShell\BloodHound.ps1:14103 char:48
+                 $Null = $WebClient.UploadString <<<< ($URI.AbsoluteUri + "db/data/batch", $JsonRequest)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

**Comment by rvazarkar** [comment] 2016-08-10 15:40
I think we have a lead on what's causing this, and we're going to take a look at it here soon. Does your data set have any names/groups with special characters in them such as parentheses?

**Comment by Beercow** [comment] 2016-08-10 15:48
At a quick glance, I see $ ! & ( ). So yest there are some special characters.

**Comment by HarmJ0y** [comment] 2016-08-10 19:23
We're working on string escape logic now, will update here if we get a fix.

**Comment by HarmJ0y** [comment] 2016-08-10 21:16
Closing this as it looks like a duplicate of https://github.com/adaptivethreat/BloodHound/issues/12 - we're working on a fix.

**Closed by HarmJ0y** 2016-08-10 21:16 UTC
